sudo: required

arch:
  packages:
  packages:
    # pacman packages
    - archiso
  script:
    - "sudo ./build.sh -v"

script:
  - "curl -s https://raw.githubusercontent.com/xeon-zolt/arch-travis/master/arch-travis.sh | bash"
