sudo: required
arch:
  packages:
     pacman packages
    - archisohttps://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
Contact GitHub API Training Shop Blog About

    - python
    #- perl
    #aur packages
    #- go-git
      script:
    - "sudo ./build.sh -v"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
