sudo: required
arch:
  packages:
    # pacman packages
    - archiso
    #- python
    #- perl
    # aur packages
    #- go-git
    # packages from papyros repo
    #- papyros-shell
  script:
    - "./build.sh -v"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
