sudo: required
arch:
  packages:
     pacman packages
    - archiso
    #- python
    #- perl
    #aur packages
    #- go-git
      script:
    - "sudo ./build.sh -v"

script:
  - "curl -s https://raw.githubusercontent.com/xeon-zolt/arch-travis/master/arch-travis.sh | bash"
