sudo: required

arch:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    # pacman packages
    - yaourt
    - archiso
  script:

    - ./build-repo
    - sudo ./build.sh -v

before_install:
- export -f travis_wait

script:
  - travis_wait 30  "curl -s https://raw.githubusercontent.com/xeon-zolt/arch-travis/master/arch-travis.sh | bash"
  
