#!/bin/python

def print_base():
    # lets i mean distro (i mean pizza)
    # what base do you want sir ?
    print ('Please enter your choice: ')
    print ("1. ARCH \n" + "2. UBUNTU \n" + "3. Quit \n")
def print_DE():
    # its time for the cheese on the pizza
    print ('Select The Destop Environment you want')
    print ('1. Gnome \n' + '2. Cinnamon \n')

while True:
    print_base()
    base = input("Choice : ")
    base = base.lower()

    if base == 'arch' or base == '1':
        print ('Selected Base Is Arch \n')

        print_DE()
        '''
        a file < packages > is present with list of base packages
        and files with DE packages are present like packages.$DE
        now we merge both of them to packages.both
        and start build
        i mean put the pizza in oven
        '''
        DE = input ('Choice : ')
        DE = DE.lower()
        import os
        if DE == 'gnome' or DE == '1':
            os.system('cat packages packages.gnome | tee packages.both')
            os.system('./build.sh -v')
        elif DE == 'cinnamon' or DE == '2':
            os.system('cat packages packages.cinnamon | tee packages.both')
            os.system('./build.sh -v')
        break

    elif base == 'ubuntu' or base == '2':
        print ('Selected Base is Ubuntu which i will add later')
        break

    elif base == 'quit' or base == '3':
        break
